[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
memory_limit = 203554432
block_base_fee_per_gas = 0
optimizer-runs = 50
max_test_rejects = 2500000000


[fuzz]
runs = 256


# See more config options https://github.com/foundry-rs/foundry/tree/master/config